language: node_js
node_js:
  - 11
  - 10
  - 9
  - 8
script:
  - 'yarn lint'
  - 'yarn test --coverage'
cache:
  - yarn
after_success:
  - 'bash <(curl -s https://codecov.io/bash)'
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'