language: node_js
node_js:
  - 11
  - 10
  - 9
  - 8
script:
  - 'yarn lint'
  - 'yarn test --coverage'
cache:
  - yarn
after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
notifications:
  email:
    recipients:
      - particle4dev@gmail.com
    on_success: never
    on_failure: always