# Config adapted from:
# https://www.electron.build/multi-platform-build#sample-travisyml-to-build-electron-app-for-macos-linux-and-windows
sudo: true

matrix:
  allow_failures:
    - os: windows
    - node_js: node
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js:
        - 11
        - 10
        - 8

    - os: linux
      services: docker
      language: node_js
      node_js:
        - 11
        - 10
        - 8
  
    - os: windows
      language: node_js
      node_js:
        - 11
        - 10
        - 8

script:
  - 'yarn lint'
  - 'yarn test --coverage'

cache:
  - yarn

after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'

notifications:
  email:
    recipients:
      - particle4dev@gmail.com
    on_success: never
    on_failure: always
